export const resultsDescriptions = [
    { description: "", label: "Year" },
    { description: "", label: "BTC Price" },
    { description: "Your annual salary + YoY increase", label: "Annual Income (Nominal)" },
    { description: "(Your annual salary + YoY increase) - Inflation", label: "Actual after inflation" },
    { description: "Aggregate reduction in purchasing power over time due to inflation", label: "Loss in purchasing power" },
    { description: "Amount of BTC acquired each year", label: "BTC acquired" },
    { description: "Total BTC accumulated through each year", label: "Aggregate" },
    { description: "Aggregate BTC * BTC price", label: "Total BTC value" },
    { description: "Loan APR * Annual income", label: "Interest owed" },
    { description: "Annual income + Interest paid", label: "Yearly loan" },
    { description: "Aggregate of yearly loans", label: "Total loan" },
    { description: "Total BTC value - Total loan", label: "Net increase $" },
    { description: "Annual income + Net increase", label: "Income + Bitcoin" },
    { description: "Net increase / Annual income", label: "Net increase %" },
    { description: "Net increase / Year", label: "Annualized BTC benefit" },
];


export const labelsOrder  = [
    "Amount down",
    "Amount financed",
    "Monthly principal",
    "Monthly interest",
    "Total monthly payment",
    "Monthly savings",
    "Interest expense paid",
    "Interest expense savings",
    "Btc investment",
    "Btc acquired",
    "Btc value",
    "Principal paid",
    "Gross home equity",
    "Appreciation",
    "Net home equity value",
    "Total asset value",
    "Plus savings",
    "Net value",
    "Multiple"
];
